version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: device_db
    environment:
      POSTGRES_DB: devicedb
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - devnet

  device-manager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: device_api
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://device_db:5432/devicedb
      SPRING_DATASOURCE_USERNAME: devuser
      SPRING_DATASOURCE_PASSWORD: devpass
    ports:
      - "8080:8080"
    networks:
      - devnet
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 15s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  devnet:
